## Challenge

If you've completed this project and you're looking for a challenge, try to implement the following using the `pandas`, `scipy`, and `seaborn` packages.

* Import both `data/control.txt' and 'data/treatment.txt' files as dataframes.
* Calculate descriptive statistics on both dataframes.
* Plot the dataframes using a seaborn method of your choice.
* Perform a t-test on both dataframes using the `ttest_ind` method from scipy.

The following documentation will be helpful in accomplishing these tasks:
* https://pandas.pydata.org/docs/user_guide/10min.html
* https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.ttest_ind.html

In [ ]:
%load_ext autoreload
%autoreload 2

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload

In [1]:
import pandas as pd 
import seaborn as sns
from scipy import stats

ModuleNotFoundError: No module named 'seaborn'

In [7]:
df1 = pd.read_csv('data/control.txt', sep='\t')
# df1
df1.describe()

          minutes
count  500.000000
mean    12.450520
std      3.261753
min      3.690000
25%     10.345000
50%     12.640000
75%     14.672500
max     21.210000

In [8]:
# TODO: implement your code here...
df2 = pd.read_csv('data/treatment.txt', sep='\t')
# df2
df2.describe()

          minutes
count  500.000000
mean    16.797080
std      2.085981
min     10.330000
25%     15.347500
50%     16.835000
75%     18.215000
max     22.850000